/* =========================================================
   RAKKEZ BLOG DATA

   This file is automatically generated.

   Do not edit manually unless you know what you are doing.
========================================================= */

window.RAKKEZ_BLOG_POSTS = [];
